version: 2

models:
  - name: cleaned_orders
    description: "Cleaned and validated orders data"
    columns:
      - name: order_id
        description: "Primary key for orders"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
      - name: order_date
        description: "Cleaned order date"
        tests:
          - not_null
      - name: total_amount
        description: "Validated total amount"
        tests:
          - not_null
          - positive_values 